services:
  db:
    volumes:
       - postgres_db:/var/lib/postgresql/data
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: ocrparking

  # admin:
  #   image: adminer
  #   restart: always
  #   depends_on: 
  #     - db
  #   ports:
  #     - 8000:8080

  # ocrparking:
  #   image: ocrparking-goit:stage1
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080

volumes:
    postgres_db:
      external: true
