"""added_is_ban_column_to_billing

Revision ID: 22c9b2a76e20
Revises: a91189dc6f54
Create Date: 2024-09-14 16:36:33.467657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c9b2a76e20'
down_revision: Union[str, None] = 'a91189dc6f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('is_ban', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing', 'is_ban')
    # ### end Alembic commands ###
